services:
  - type: web
    name: ogsun-mache-lakay
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: ADMIN_EMAIL
        value: metelluscarlinsky@gmail.com
      - key: ADMIN_PASSWORD
        value: OGPLUG45